import type { ExerciseLibraryItem } from "./types";

const groups: Record<
  string,
  Array<[string, string, ExerciseLibraryItem["movement"]]>
> = {
  Pecho: [
    ["Press banca con barra", "Barra", "empuje"],
    ["Press banca con mancuernas", "Mancuernas", "empuje"],
    ["Press inclinado con barra", "Barra", "empuje"],
    ["Press inclinado con mancuernas", "Mancuernas", "empuje"],
    ["Press declinado con barra", "Barra", "empuje"],
    ["Press pecho en máquina", "Máquina", "empuje"],
    ["Press convergente de pecho", "Máquina", "empuje"],
    ["Fondos para pecho", "Peso corporal", "empuje"],
    ["Cruce de poleas alto a bajo", "Poleas", "aislamiento"],
    ["Aperturas en máquina", "Máquina", "aislamiento"],
    ["Aperturas con mancuernas", "Mancuernas", "aislamiento"],
    ["Pullover con mancuerna", "Mancuerna", "tiron"],
  ],
  Espalda: [
    ["Dominadas pronas", "Peso corporal", "tiron"],
    ["Dominadas neutras", "Peso corporal", "tiron"],
    ["Dominadas asistidas", "Máquina", "tiron"],
    ["Jalón al pecho", "Polea", "tiron"],
    ["Jalón agarre neutro", "Polea", "tiron"],
    ["Jalón unilateral", "Polea", "tiron"],
    ["Remo con barra", "Barra", "tiron"],
    ["Remo con mancuerna", "Mancuerna", "tiron"],
    ["Remo con pecho apoyado", "Máquina", "tiron"],
    ["Remo en polea baja", "Polea", "tiron"],
    ["Remo unilateral en polea", "Polea", "tiron"],
    ["Pullover en polea", "Polea", "tiron"],
  ],
  Hombro: [
    ["Press militar con barra", "Barra", "empuje"],
    ["Press militar con mancuernas", "Mancuernas", "empuje"],
    ["Press Arnold", "Mancuernas", "empuje"],
    ["Press hombro en máquina", "Máquina", "empuje"],
    ["Elevaciones laterales con mancuernas", "Mancuernas", "aislamiento"],
    ["Elevaciones laterales en polea", "Polea", "aislamiento"],
    ["Elevaciones laterales en máquina", "Máquina", "aislamiento"],
    ["Elevaciones frontales", "Mancuernas", "aislamiento"],
    ["Pájaros con mancuernas", "Mancuernas", "aislamiento"],
    ["Pájaros en máquina", "Máquina", "aislamiento"],
    ["Face pull", "Polea", "tiron"],
    ["Remo al mentón con cuerda", "Polea", "tiron"],
  ],
  Bíceps: [
    ["Curl con barra recta", "Barra", "aislamiento"],
    ["Curl con barra EZ", "Barra", "aislamiento"],
    ["Curl alterno con mancuernas", "Mancuernas", "aislamiento"],
    ["Curl inclinado", "Mancuernas", "aislamiento"],
    ["Curl predicador", "Máquina", "aislamiento"],
    ["Curl predicador con barra EZ", "Barra", "aislamiento"],
    ["Curl martillo", "Mancuernas", "aislamiento"],
    ["Curl martillo con cuerda", "Polea", "aislamiento"],
    ["Curl en polea baja", "Polea", "aislamiento"],
    ["Curl unilateral en polea", "Polea", "aislamiento"],
    ["Curl concentrado", "Mancuerna", "aislamiento"],
    ["Curl spider", "Mancuernas", "aislamiento"],
  ],
  Tríceps: [
    ["Press cerrado", "Barra", "empuje"],
    ["Fondos para tríceps", "Peso corporal", "empuje"],
    ["Extensión de tríceps con cuerda", "Polea", "aislamiento"],
    ["Extensión de tríceps con barra", "Polea", "aislamiento"],
    ["Extensión unilateral en polea", "Polea", "aislamiento"],
    ["Extensión por encima de la cabeza con cuerda", "Polea", "aislamiento"],
    [
      "Extensión por encima de la cabeza con mancuerna",
      "Mancuerna",
      "aislamiento",
    ],
    ["Press francés", "Barra EZ", "aislamiento"],
    ["Rompecráneos con mancuernas", "Mancuernas", "aislamiento"],
    ["Patada de tríceps", "Mancuerna", "aislamiento"],
    ["Extensión en máquina", "Máquina", "aislamiento"],
  ],
  Cuádriceps: [
    ["Sentadilla trasera", "Barra", "sentadilla"],
    ["Sentadilla frontal", "Barra", "sentadilla"],
    ["Sentadilla en multipower", "Multipower", "sentadilla"],
    ["Sentadilla hack", "Máquina", "sentadilla"],
    ["Prensa inclinada", "Máquina", "sentadilla"],
    ["Prensa unilateral", "Máquina", "sentadilla"],
    ["Sentadilla goblet", "Mancuerna", "sentadilla"],
    ["Sentadilla búlgara", "Mancuernas", "sentadilla"],
    ["Step-up", "Mancuernas", "sentadilla"],
    ["Extensión de cuádriceps", "Máquina", "aislamiento"],
    ["Extensión unilateral de cuádriceps", "Máquina", "aislamiento"],
    ["Sissy squat asistida", "Peso corporal", "sentadilla"],
  ],
  Femoral: [
    ["Peso muerto rumano con barra", "Barra", "bisagra"],
    ["Peso muerto rumano con mancuernas", "Mancuernas", "bisagra"],
    ["Peso muerto a una pierna", "Mancuerna", "bisagra"],
    ["Buenos días", "Barra", "bisagra"],
    ["Buenos días en multipower", "Multipower", "bisagra"],
    ["Curl femoral tumbado", "Máquina", "aislamiento"],
    ["Curl femoral sentado", "Máquina", "aislamiento"],
    ["Curl femoral unilateral", "Máquina", "aislamiento"],
    ["Nordic curl asistido", "Peso corporal", "aislamiento"],
    ["Pull-through", "Polea", "bisagra"],
    ["Curl femoral con fitball", "Fitball", "aislamiento"],
  ],
  Glúteo: [
    ["Hip thrust con barra", "Barra", "bisagra"],
    ["Hip thrust en máquina", "Máquina", "bisagra"],
    ["Puente de glúteo", "Peso corporal", "bisagra"],
    ["Puente de glúteo con barra", "Barra", "bisagra"],
    ["Patada de glúteo en polea", "Polea", "aislamiento"],
    ["Abducción de cadera en máquina", "Máquina", "aislamiento"],
    ["Abducción de cadera en polea", "Polea", "aislamiento"],
    ["Sentadilla búlgara inclinada", "Mancuernas", "sentadilla"],
    ["Step-up alto", "Mancuernas", "sentadilla"],
    ["Zancada larga", "Mancuernas", "sentadilla"],
    ["Pull-through", "Polea", "bisagra"],
  ],
  Gemelos: [
    ["Elevación de gemelos de pie", "Máquina", "aislamiento"],
    ["Gemelo sentado", "Máquina", "aislamiento"],
    ["Gemelo en prensa", "Prensa", "aislamiento"],
    ["Gemelo unilateral de pie", "Mancuerna", "aislamiento"],
    ["Gemelo en multipower", "Multipower", "aislamiento"],
    ["Gemelo en máquina hack", "Máquina", "aislamiento"],
    ["Gemelo en escalón", "Peso corporal", "aislamiento"],
    ["Tibial anterior", "Máquina", "aislamiento"],
  ],
  Abdominales: [
    ["Crunch en polea", "Polea", "core"],
    ["Crunch en máquina", "Máquina", "core"],
    ["Crunch en suelo", "Peso corporal", "core"],
    ["Elevación de piernas", "Peso corporal", "core"],
    ["Elevación de rodillas colgado", "Peso corporal", "core"],
    ["Rueda abdominal", "Rueda", "core"],
    ["Plancha frontal", "Peso corporal", "core"],
    ["Plancha lateral", "Peso corporal", "core"],
    ["Pallof press", "Polea", "core"],
    ["Dead bug", "Peso corporal", "core"],
    ["Hollow body hold", "Peso corporal", "core"],
  ],
  Aductores: [
    ["Aducción de cadera en máquina", "Máquina", "aislamiento"],
    ["Aducción de cadera en polea", "Polea", "aislamiento"],
    ["Copenhagen plank", "Peso corporal", "core"],
    ["Zancada lateral", "Mancuernas", "sentadilla"],
    ["Sentadilla sumo", "Mancuerna", "sentadilla"],
    ["Peso muerto sumo", "Barra", "bisagra"],
  ],
  Antebrazo: [
    ["Curl de muñeca", "Barra", "aislamiento"],
    ["Curl inverso de muñeca", "Barra", "aislamiento"],
    ["Curl inverso", "Barra EZ", "aislamiento"],
    ["Farmer walk", "Mancuernas", "tiron"],
    ["Agarre estático", "Barra", "tiron"],
    ["Pinza con discos", "Discos", "aislamiento"],
  ],
};

export const EXERCISE_LIBRARY: ExerciseLibraryItem[] = Object.entries(
  groups,
).flatMap(([muscleGroup, exercises]) =>
  exercises.map(([name, equipment, movement]) => ({
    name,
    muscleGroup,
    equipment,
    movement,
  })),
);

export const EXERCISE_MUSCLE_GROUPS = Object.keys(groups);
