import type { PlannedMeal } from "@/features/nutrition-planner/types";

export type RecipeTemplate = Omit<PlannedMeal, "id">;

export const RECIPE_CATALOG: RecipeTemplate[] = [
  {
    mealType: "Desayuno",
    name: "Tostadas con pavo y tomate",
    description: "Desayuno salado con pan, proteína magra y fruta.",
    calories: 430,
    protein: 29,
    carbs: 55,
    fat: 10,
    ingredients: [
      {
        name: "Pan integral",
        quantity: 2,
        unit: "rebanada",
        category: "Carbohidratos",
      },
      {
        name: "Pechuga de pavo",
        quantity: 90,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Tomate", quantity: 120, unit: "g", category: "Fruta y verdura" },
      {
        name: "Aceite de oliva",
        quantity: 8,
        unit: "ml",
        category: "Despensa",
      },
      {
        name: "Plátano",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
    ],
    preparation: [
      "Tuesta el pan.",
      "Añade tomate, aceite y pavo.",
      "Sirve con el plátano.",
    ],
    tags: ["pan", "rápido", "alto en proteína"],
  },
  {
    mealType: "Desayuno",
    name: "Yogur con avena y frutos rojos",
    description: "Bol rápido y saciante para empezar el día.",
    calories: 410,
    protein: 28,
    carbs: 52,
    fat: 9,
    ingredients: [
      {
        name: "Yogur alto en proteína",
        quantity: 250,
        unit: "g",
        category: "Lácteos",
      },
      {
        name: "Copos de avena",
        quantity: 55,
        unit: "g",
        category: "Carbohidratos",
      },
      {
        name: "Frutos rojos",
        quantity: 120,
        unit: "g",
        category: "Fruta y verdura",
      },
      { name: "Miel", quantity: 10, unit: "g", category: "Despensa" },
    ],
    preparation: [
      "Mezcla el yogur y la avena.",
      "Añade los frutos rojos y la miel.",
    ],
    tags: ["sin cocinar", "alto en proteína"],
  },
  {
    mealType: "Media mañana",
    name: "Bocadillo pequeño de jamón y queso",
    description: "Tentempié práctico con pan y proteína.",
    calories: 330,
    protein: 22,
    carbs: 36,
    fat: 11,
    ingredients: [
      { name: "Pan", quantity: 90, unit: "g", category: "Carbohidratos" },
      { name: "Jamón cocido", quantity: 70, unit: "g", category: "Proteínas" },
      {
        name: "Queso bajo en grasa",
        quantity: 30,
        unit: "g",
        category: "Lácteos",
      },
    ],
    preparation: ["Abre el pan.", "Rellena con jamón y queso."],
    tags: ["pan", "portable"],
  },
  {
    mealType: "Media mañana",
    name: "Yogur proteico y manzana",
    description: "Opción ligera y fácil de llevar.",
    calories: 250,
    protein: 22,
    carbs: 31,
    fat: 4,
    ingredients: [
      {
        name: "Yogur alto en proteína",
        quantity: 200,
        unit: "g",
        category: "Lácteos",
      },
      {
        name: "Manzana",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
    ],
    preparation: ["Sirve el yogur junto a la manzana."],
    tags: ["sin cocinar", "portable"],
  },
  {
    mealType: "Comida",
    name: "Arroz con pollo y verduras",
    description: "Plato completo para días de entrenamiento.",
    calories: 690,
    protein: 52,
    carbs: 82,
    fat: 17,
    ingredients: [
      {
        name: "Pechuga de pollo",
        quantity: 190,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Arroz", quantity: 95, unit: "g", category: "Carbohidratos" },
      {
        name: "Calabacín",
        quantity: 150,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Pimiento",
        quantity: 100,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Aceite de oliva",
        quantity: 12,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Cuece el arroz.",
      "Saltea pollo y verduras con aceite.",
      "Mezcla y sazona.",
    ],
    tags: ["entrenamiento", "alto en proteína"],
  },
  {
    mealType: "Comida",
    name: "Pasta boloñesa ligera",
    description: "Pasta con carne magra y tomate.",
    calories: 720,
    protein: 49,
    carbs: 88,
    fat: 19,
    ingredients: [
      { name: "Pasta", quantity: 100, unit: "g", category: "Carbohidratos" },
      {
        name: "Carne picada magra",
        quantity: 180,
        unit: "g",
        category: "Proteínas",
      },
      {
        name: "Tomate triturado",
        quantity: 200,
        unit: "g",
        category: "Fruta y verdura",
      },
      { name: "Cebolla", quantity: 80, unit: "g", category: "Fruta y verdura" },
      {
        name: "Aceite de oliva",
        quantity: 10,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Cuece la pasta.",
      "Sofríe cebolla y carne.",
      "Añade tomate y mezcla con la pasta.",
    ],
    tags: ["alto en proteína", "familiar"],
  },
  {
    mealType: "Comida",
    name: "Patatas asadas con pavo",
    description: "Comida saciante con proteína magra.",
    calories: 650,
    protein: 50,
    carbs: 73,
    fat: 17,
    ingredients: [
      {
        name: "Pechuga de pavo",
        quantity: 200,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Patata", quantity: 380, unit: "g", category: "Carbohidratos" },
      {
        name: "Ensalada variada",
        quantity: 180,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Aceite de oliva",
        quantity: 12,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Asa las patatas.",
      "Cocina el pavo a la plancha.",
      "Sirve con ensalada.",
    ],
    tags: ["sin pescado", "alto en proteína"],
  },
  {
    mealType: "Merienda",
    name: "Sándwich de tortilla francesa",
    description: "Merienda completa y sencilla.",
    calories: 380,
    protein: 25,
    carbs: 34,
    fat: 16,
    ingredients: [
      {
        name: "Pan integral",
        quantity: 2,
        unit: "rebanada",
        category: "Carbohidratos",
      },
      { name: "Huevo", quantity: 2, unit: "unidad", category: "Proteínas" },
      {
        name: "Claras de huevo",
        quantity: 120,
        unit: "ml",
        category: "Proteínas",
      },
      { name: "Tomate", quantity: 70, unit: "g", category: "Fruta y verdura" },
    ],
    preparation: [
      "Prepara la tortilla con huevo y claras.",
      "Monta el sándwich con tomate.",
    ],
    tags: ["pan", "alto en proteína"],
  },
  {
    mealType: "Merienda",
    name: "Batido de plátano y yogur",
    description: "Merienda rápida para después de entrenar.",
    calories: 360,
    protein: 28,
    carbs: 54,
    fat: 5,
    ingredients: [
      {
        name: "Yogur alto en proteína",
        quantity: 250,
        unit: "g",
        category: "Lácteos",
      },
      {
        name: "Plátano",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
      {
        name: "Copos de avena",
        quantity: 35,
        unit: "g",
        category: "Carbohidratos",
      },
      { name: "Leche", quantity: 150, unit: "ml", category: "Lácteos" },
    ],
    preparation: [
      "Tritura todos los ingredientes hasta obtener una textura homogénea.",
    ],
    tags: ["postentreno", "rápido"],
  },
  {
    mealType: "Cena",
    name: "Tortilla de patata ligera con ensalada",
    description: "Cena casera con cantidad controlada de aceite.",
    calories: 560,
    protein: 35,
    carbs: 54,
    fat: 23,
    ingredients: [
      { name: "Huevo", quantity: 3, unit: "unidad", category: "Proteínas" },
      {
        name: "Claras de huevo",
        quantity: 150,
        unit: "ml",
        category: "Proteínas",
      },
      { name: "Patata", quantity: 260, unit: "g", category: "Carbohidratos" },
      {
        name: "Ensalada variada",
        quantity: 180,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Aceite de oliva",
        quantity: 8,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Cocina la patata al microondas o al horno.",
      "Cuaja con huevo y claras.",
      "Sirve con ensalada.",
    ],
    tags: ["sin pescado", "cena"],
  },
  {
    mealType: "Cena",
    name: "Wraps de pollo y verduras",
    description: "Cena rápida con pollo y vegetales.",
    calories: 580,
    protein: 46,
    carbs: 61,
    fat: 17,
    ingredients: [
      {
        name: "Tortilla de trigo",
        quantity: 2,
        unit: "unidad",
        category: "Carbohidratos",
      },
      {
        name: "Pechuga de pollo",
        quantity: 170,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Lechuga", quantity: 80, unit: "g", category: "Fruta y verdura" },
      { name: "Tomate", quantity: 100, unit: "g", category: "Fruta y verdura" },
      { name: "Yogur natural", quantity: 60, unit: "g", category: "Lácteos" },
    ],
    preparation: [
      "Cocina el pollo.",
      "Rellena las tortillas con verduras y pollo.",
      "Añade yogur como salsa.",
    ],
    tags: ["rápido", "alto en proteína"],
  },
  {
    mealType: "Cena",
    name: "Hamburguesa casera con patata",
    description: "Cena completa con carne magra y pan.",
    calories: 670,
    protein: 48,
    carbs: 70,
    fat: 22,
    ingredients: [
      {
        name: "Carne picada magra",
        quantity: 180,
        unit: "g",
        category: "Proteínas",
      },
      {
        name: "Pan de hamburguesa",
        quantity: 1,
        unit: "unidad",
        category: "Carbohidratos",
      },
      { name: "Patata", quantity: 260, unit: "g", category: "Carbohidratos" },
      { name: "Lechuga", quantity: 50, unit: "g", category: "Fruta y verdura" },
      { name: "Tomate", quantity: 80, unit: "g", category: "Fruta y verdura" },
    ],
    preparation: [
      "Forma y cocina la hamburguesa.",
      "Hornea la patata.",
      "Monta con lechuga y tomate.",
    ],
    tags: ["pan", "fin de semana"],
  },

  {
    mealType: "Desayuno",
    name: "Tostadas de huevo y aguacate",
    description: "Pan tostado con huevo, aguacate y tomate.",
    calories: 445,
    protein: 24,
    carbs: 43,
    fat: 20,
    ingredients: [
      {
        name: "Pan integral",
        quantity: 2,
        unit: "rebanada",
        category: "Carbohidratos",
      },
      { name: "Huevo", quantity: 2, unit: "unidad", category: "Proteínas" },
      {
        name: "Aguacate",
        quantity: 60,
        unit: "g",
        category: "Fruta y verdura",
      },
      { name: "Tomate", quantity: 100, unit: "g", category: "Fruta y verdura" },
    ],
    preparation: [
      "Tuesta el pan.",
      "Cocina los huevos y sirve con aguacate y tomate.",
    ],
    tags: ["pan", "alto en proteína"],
  },
  {
    mealType: "Desayuno",
    name: "Porridge de manzana y canela",
    description: "Avena cremosa con leche, manzana y yogur.",
    calories: 420,
    protein: 27,
    carbs: 60,
    fat: 9,
    ingredients: [
      {
        name: "Copos de avena",
        quantity: 55,
        unit: "g",
        category: "Carbohidratos",
      },
      { name: "Leche", quantity: 200, unit: "ml", category: "Lácteos" },
      {
        name: "Manzana",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
      {
        name: "Yogur alto en proteína",
        quantity: 150,
        unit: "g",
        category: "Lácteos",
      },
      { name: "Canela", quantity: 2, unit: "g", category: "Despensa" },
    ],
    preparation: [
      "Cuece la avena con leche.",
      "Añade manzana, canela y yogur.",
    ],
    tags: ["caliente", "saciante"],
  },
  {
    mealType: "Desayuno",
    name: "Tortilla de claras con pavo",
    description: "Tortilla ligera acompañada de pan y fruta.",
    calories: 435,
    protein: 38,
    carbs: 45,
    fat: 10,
    ingredients: [
      {
        name: "Claras de huevo",
        quantity: 180,
        unit: "ml",
        category: "Proteínas",
      },
      {
        name: "Pechuga de pavo",
        quantity: 70,
        unit: "g",
        category: "Proteínas",
      },
      {
        name: "Pan integral",
        quantity: 2,
        unit: "rebanada",
        category: "Carbohidratos",
      },
      {
        name: "Naranja",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
    ],
    preparation: ["Cuaja las claras con el pavo.", "Sirve con pan y naranja."],
    tags: ["pan", "alto en proteína"],
  },
  {
    mealType: "Desayuno",
    name: "Pancakes de avena y yogur",
    description: "Tortitas de avena con yogur y plátano.",
    calories: 455,
    protein: 31,
    carbs: 61,
    fat: 8,
    ingredients: [
      {
        name: "Copos de avena",
        quantity: 60,
        unit: "g",
        category: "Carbohidratos",
      },
      { name: "Huevo", quantity: 1, unit: "unidad", category: "Proteínas" },
      {
        name: "Yogur alto en proteína",
        quantity: 180,
        unit: "g",
        category: "Lácteos",
      },
      {
        name: "Plátano",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
    ],
    preparation: [
      "Tritura avena, huevo y parte del yogur.",
      "Cocina las tortitas y termina con plátano y yogur.",
    ],
    tags: ["dulce", "alto en proteína"],
  },
  {
    mealType: "Desayuno",
    name: "Mollete de pollo y tomate",
    description: "Desayuno salado con pan, pollo y tomate.",
    calories: 465,
    protein: 36,
    carbs: 54,
    fat: 10,
    ingredients: [
      {
        name: "Pan integral",
        quantity: 2,
        unit: "rebanada",
        category: "Carbohidratos",
      },
      {
        name: "Pechuga de pollo",
        quantity: 100,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Tomate", quantity: 120, unit: "g", category: "Fruta y verdura" },
      {
        name: "Aceite de oliva",
        quantity: 7,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Cocina el pollo y córtalo.",
      "Monta sobre el pan con tomate y aceite.",
    ],
    tags: ["pan", "salado"],
  },
  {
    mealType: "Desayuno",
    name: "Yogur con kiwi, avena y cacao",
    description: "Bol fresco de yogur, fruta y avena.",
    calories: 405,
    protein: 30,
    carbs: 50,
    fat: 8,
    ingredients: [
      {
        name: "Yogur alto en proteína",
        quantity: 250,
        unit: "g",
        category: "Lácteos",
      },
      {
        name: "Kiwi",
        quantity: 2,
        unit: "unidad",
        category: "Fruta y verdura",
      },
      {
        name: "Copos de avena",
        quantity: 45,
        unit: "g",
        category: "Carbohidratos",
      },
      { name: "Cacao puro", quantity: 5, unit: "g", category: "Despensa" },
    ],
    preparation: ["Mezcla yogur y avena.", "Añade kiwi y cacao."],
    tags: ["sin cocinar", "rápido"],
  },
  {
    mealType: "Media mañana",
    name: "Yogur y manzana con avena",
    description: "Tentempié sencillo rico en proteína.",
    calories: 300,
    protein: 24,
    carbs: 39,
    fat: 5,
    ingredients: [
      {
        name: "Yogur alto en proteína",
        quantity: 200,
        unit: "g",
        category: "Lácteos",
      },
      {
        name: "Manzana",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
      {
        name: "Copos de avena",
        quantity: 25,
        unit: "g",
        category: "Carbohidratos",
      },
    ],
    preparation: ["Mezcla todo y sirve frío."],
    tags: ["sin cocinar"],
  },
  {
    mealType: "Media mañana",
    name: "Tostada de pavo y queso fresco",
    description: "Pan con proteína magra y queso fresco.",
    calories: 315,
    protein: 25,
    carbs: 32,
    fat: 9,
    ingredients: [
      {
        name: "Pan integral",
        quantity: 2,
        unit: "rebanada",
        category: "Carbohidratos",
      },
      {
        name: "Pechuga de pavo",
        quantity: 70,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Queso fresco", quantity: 50, unit: "g", category: "Lácteos" },
      { name: "Tomate", quantity: 60, unit: "g", category: "Fruta y verdura" },
    ],
    preparation: ["Tuesta el pan y monta todos los ingredientes."],
    tags: ["pan", "rápido"],
  },
  {
    mealType: "Media mañana",
    name: "Batido de yogur, fresa y avena",
    description: "Batido fresco para llevar.",
    calories: 320,
    protein: 28,
    carbs: 44,
    fat: 4,
    ingredients: [
      {
        name: "Yogur alto en proteína",
        quantity: 200,
        unit: "g",
        category: "Lácteos",
      },
      { name: "Fresas", quantity: 150, unit: "g", category: "Fruta y verdura" },
      {
        name: "Copos de avena",
        quantity: 30,
        unit: "g",
        category: "Carbohidratos",
      },
      { name: "Leche", quantity: 100, unit: "ml", category: "Lácteos" },
    ],
    preparation: ["Tritura todos los ingredientes."],
    tags: ["rápido", "postentreno"],
  },
  {
    mealType: "Media mañana",
    name: "Queso fresco, pavo y fruta",
    description: "Combinación fría y saciante.",
    calories: 290,
    protein: 30,
    carbs: 25,
    fat: 7,
    ingredients: [
      { name: "Queso fresco", quantity: 100, unit: "g", category: "Lácteos" },
      {
        name: "Pechuga de pavo",
        quantity: 70,
        unit: "g",
        category: "Proteínas",
      },
      {
        name: "Pera",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
    ],
    preparation: ["Sirve todo en un plato o táper."],
    tags: ["sin cocinar", "alto en proteína"],
  },
  {
    mealType: "Media mañana",
    name: "Mini wrap de pollo",
    description: "Wrap pequeño con pollo y verduras.",
    calories: 335,
    protein: 28,
    carbs: 34,
    fat: 9,
    ingredients: [
      {
        name: "Tortilla de trigo",
        quantity: 1,
        unit: "unidad",
        category: "Carbohidratos",
      },
      {
        name: "Pechuga de pollo",
        quantity: 90,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Lechuga", quantity: 50, unit: "g", category: "Fruta y verdura" },
      { name: "Tomate", quantity: 60, unit: "g", category: "Fruta y verdura" },
    ],
    preparation: ["Cocina el pollo.", "Rellena y enrolla la tortilla."],
    tags: ["rápido"],
  },
  {
    mealType: "Media mañana",
    name: "Tortilla francesa y fruta",
    description: "Opción sencilla y rica en proteína.",
    calories: 285,
    protein: 24,
    carbs: 26,
    fat: 9,
    ingredients: [
      { name: "Huevo", quantity: 2, unit: "unidad", category: "Proteínas" },
      {
        name: "Claras de huevo",
        quantity: 80,
        unit: "ml",
        category: "Proteínas",
      },
      {
        name: "Plátano",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
    ],
    preparation: [
      "Haz la tortilla con huevo y claras.",
      "Acompaña con plátano.",
    ],
    tags: ["rápido"],
  },
  {
    mealType: "Comida",
    name: "Ternera salteada con arroz y verduras",
    description: "Plato completo de arroz, ternera y verduras.",
    calories: 690,
    protein: 48,
    carbs: 78,
    fat: 18,
    ingredients: [
      {
        name: "Ternera magra",
        quantity: 180,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Arroz", quantity: 90, unit: "g", category: "Carbohidratos" },
      {
        name: "Pimiento",
        quantity: 100,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Calabacín",
        quantity: 150,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Aceite de oliva",
        quantity: 10,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Cuece el arroz.",
      "Saltea ternera y verduras.",
      "Mezcla y sirve.",
    ],
    tags: ["alto en proteína", "entrenamiento"],
  },
  {
    mealType: "Comida",
    name: "Pollo al curry con arroz",
    description: "Pollo especiado con arroz y verduras.",
    calories: 675,
    protein: 53,
    carbs: 79,
    fat: 14,
    ingredients: [
      {
        name: "Pechuga de pollo",
        quantity: 210,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Arroz", quantity: 90, unit: "g", category: "Carbohidratos" },
      { name: "Leche", quantity: 100, unit: "ml", category: "Lácteos" },
      {
        name: "Pimiento",
        quantity: 100,
        unit: "g",
        category: "Fruta y verdura",
      },
      { name: "Curry", quantity: 5, unit: "g", category: "Despensa" },
    ],
    preparation: [
      "Cuece el arroz.",
      "Cocina el pollo con pimiento y curry.",
      "Añade leche y reduce la salsa.",
    ],
    tags: ["alto en proteína", "especiado"],
  },
  {
    mealType: "Comida",
    name: "Lomo de cerdo con patata y pimientos",
    description: "Plato casero con carne magra y patata.",
    calories: 665,
    protein: 50,
    carbs: 64,
    fat: 20,
    ingredients: [
      {
        name: "Lomo de cerdo",
        quantity: 200,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Patata", quantity: 350, unit: "g", category: "Carbohidratos" },
      {
        name: "Pimiento",
        quantity: 150,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Aceite de oliva",
        quantity: 12,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Asa la patata.",
      "Cocina el lomo y los pimientos a la plancha.",
    ],
    tags: ["casero", "sin pescado"],
  },
  {
    mealType: "Comida",
    name: "Pasta cremosa de pollo y champiñones",
    description: "Pasta con pollo, champiñones y salsa ligera.",
    calories: 710,
    protein: 55,
    carbs: 84,
    fat: 16,
    ingredients: [
      { name: "Pasta", quantity: 100, unit: "g", category: "Carbohidratos" },
      {
        name: "Pechuga de pollo",
        quantity: 190,
        unit: "g",
        category: "Proteínas",
      },
      {
        name: "Champiñones",
        quantity: 150,
        unit: "g",
        category: "Fruta y verdura",
      },
      { name: "Yogur natural", quantity: 80, unit: "g", category: "Lácteos" },
      {
        name: "Aceite de oliva",
        quantity: 8,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Cuece la pasta.",
      "Saltea pollo y champiñones.",
      "Añade yogur fuera del fuego y mezcla.",
    ],
    tags: ["alto en proteína", "familiar"],
  },
  {
    mealType: "Comida",
    name: "Cuscús de pavo y verduras",
    description: "Cuscús rápido con pavo y verduras salteadas.",
    calories: 650,
    protein: 49,
    carbs: 77,
    fat: 13,
    ingredients: [
      { name: "Cuscús", quantity: 90, unit: "g", category: "Carbohidratos" },
      {
        name: "Pechuga de pavo",
        quantity: 200,
        unit: "g",
        category: "Proteínas",
      },
      {
        name: "Calabacín",
        quantity: 120,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Zanahoria",
        quantity: 100,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Aceite de oliva",
        quantity: 10,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Hidrata el cuscús.",
      "Saltea pavo y verduras.",
      "Mezcla y sazona.",
    ],
    tags: ["rápido", "alto en proteína"],
  },
  {
    mealType: "Comida",
    name: "Arroz tres delicias casero con pollo",
    description: "Versión casera con arroz, huevo, pollo y verduras.",
    calories: 700,
    protein: 52,
    carbs: 82,
    fat: 16,
    ingredients: [
      { name: "Arroz", quantity: 95, unit: "g", category: "Carbohidratos" },
      {
        name: "Pechuga de pollo",
        quantity: 170,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Huevo", quantity: 1, unit: "unidad", category: "Proteínas" },
      {
        name: "Zanahoria",
        quantity: 80,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Guisantes",
        quantity: 60,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Aceite de oliva",
        quantity: 8,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Cuece el arroz.",
      "Saltea pollo y verduras.",
      "Añade huevo y arroz y cocina todo junto.",
    ],
    tags: ["familiar", "entrenamiento"],
  },
  {
    mealType: "Comida",
    name: "Albóndigas de ternera con patata",
    description: "Albóndigas caseras con salsa de tomate y patata.",
    calories: 705,
    protein: 51,
    carbs: 69,
    fat: 22,
    ingredients: [
      {
        name: "Carne picada magra",
        quantity: 190,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Patata", quantity: 320, unit: "g", category: "Carbohidratos" },
      {
        name: "Tomate triturado",
        quantity: 180,
        unit: "g",
        category: "Fruta y verdura",
      },
      { name: "Cebolla", quantity: 70, unit: "g", category: "Fruta y verdura" },
      {
        name: "Aceite de oliva",
        quantity: 10,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Forma las albóndigas.",
      "Cocina con tomate y cebolla.",
      "Acompaña con patata asada.",
    ],
    tags: ["casero", "alto en proteína"],
  },
  {
    mealType: "Merienda",
    name: "Yogur con plátano y cacao",
    description: "Merienda dulce rica en proteína.",
    calories: 345,
    protein: 29,
    carbs: 50,
    fat: 5,
    ingredients: [
      {
        name: "Yogur alto en proteína",
        quantity: 250,
        unit: "g",
        category: "Lácteos",
      },
      {
        name: "Plátano",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
      { name: "Cacao puro", quantity: 5, unit: "g", category: "Despensa" },
      {
        name: "Copos de avena",
        quantity: 20,
        unit: "g",
        category: "Carbohidratos",
      },
    ],
    preparation: ["Mezcla todos los ingredientes."],
    tags: ["sin cocinar", "dulce"],
  },
  {
    mealType: "Merienda",
    name: "Sándwich de pollo y queso",
    description: "Sándwich completo para una merienda potente.",
    calories: 420,
    protein: 35,
    carbs: 40,
    fat: 13,
    ingredients: [
      {
        name: "Pan integral",
        quantity: 2,
        unit: "rebanada",
        category: "Carbohidratos",
      },
      {
        name: "Pechuga de pollo",
        quantity: 100,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Queso light", quantity: 30, unit: "g", category: "Lácteos" },
      { name: "Tomate", quantity: 60, unit: "g", category: "Fruta y verdura" },
    ],
    preparation: ["Cocina el pollo.", "Monta el sándwich con queso y tomate."],
    tags: ["pan", "alto en proteína"],
  },
  {
    mealType: "Merienda",
    name: "Tortilla de trigo con pavo y queso",
    description: "Wrap frío y rápido.",
    calories: 390,
    protein: 31,
    carbs: 39,
    fat: 11,
    ingredients: [
      {
        name: "Tortilla de trigo",
        quantity: 1,
        unit: "unidad",
        category: "Carbohidratos",
      },
      {
        name: "Pechuga de pavo",
        quantity: 90,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Queso fresco", quantity: 50, unit: "g", category: "Lácteos" },
      { name: "Lechuga", quantity: 50, unit: "g", category: "Fruta y verdura" },
    ],
    preparation: ["Rellena y enrolla la tortilla."],
    tags: ["rápido"],
  },
  {
    mealType: "Merienda",
    name: "Porridge proteico de cacao",
    description: "Avena caliente con cacao y yogur.",
    calories: 370,
    protein: 30,
    carbs: 48,
    fat: 7,
    ingredients: [
      {
        name: "Copos de avena",
        quantity: 45,
        unit: "g",
        category: "Carbohidratos",
      },
      { name: "Leche", quantity: 180, unit: "ml", category: "Lácteos" },
      {
        name: "Yogur alto en proteína",
        quantity: 150,
        unit: "g",
        category: "Lácteos",
      },
      { name: "Cacao puro", quantity: 5, unit: "g", category: "Despensa" },
    ],
    preparation: [
      "Cuece la avena con leche.",
      "Añade cacao y termina con yogur.",
    ],
    tags: ["caliente", "postentreno"],
  },
  {
    mealType: "Merienda",
    name: "Queso fresco batido con fruta",
    description: "Bol rápido y fresco.",
    calories: 315,
    protein: 30,
    carbs: 38,
    fat: 3,
    ingredients: [
      {
        name: "Queso fresco batido",
        quantity: 250,
        unit: "g",
        category: "Lácteos",
      },
      {
        name: "Pera",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
      {
        name: "Copos de avena",
        quantity: 25,
        unit: "g",
        category: "Carbohidratos",
      },
    ],
    preparation: ["Mezcla el queso con avena y añade la fruta."],
    tags: ["sin cocinar", "alto en proteína"],
  },
  {
    mealType: "Merienda",
    name: "Tostada de jamón y tomate",
    description: "Clásico rápido para cualquier momento.",
    calories: 350,
    protein: 25,
    carbs: 40,
    fat: 9,
    ingredients: [
      {
        name: "Pan integral",
        quantity: 2,
        unit: "rebanada",
        category: "Carbohidratos",
      },
      { name: "Jamón serrano", quantity: 45, unit: "g", category: "Proteínas" },
      { name: "Tomate", quantity: 120, unit: "g", category: "Fruta y verdura" },
      {
        name: "Aceite de oliva",
        quantity: 5,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: ["Tuesta el pan.", "Añade tomate, aceite y jamón."],
    tags: ["pan", "rápido"],
  },
  {
    mealType: "Cena",
    name: "Pollo al horno con boniato",
    description: "Cena ligera y completa.",
    calories: 585,
    protein: 52,
    carbs: 58,
    fat: 14,
    ingredients: [
      {
        name: "Pechuga de pollo",
        quantity: 210,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Boniato", quantity: 300, unit: "g", category: "Carbohidratos" },
      {
        name: "Ensalada variada",
        quantity: 180,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Aceite de oliva",
        quantity: 10,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: ["Hornea pollo y boniato.", "Sirve con ensalada."],
    tags: ["ligera", "alto en proteína"],
  },
  {
    mealType: "Cena",
    name: "Revuelto de huevo, claras y pavo",
    description: "Cena proteica lista en pocos minutos.",
    calories: 470,
    protein: 48,
    carbs: 28,
    fat: 17,
    ingredients: [
      { name: "Huevo", quantity: 2, unit: "unidad", category: "Proteínas" },
      {
        name: "Claras de huevo",
        quantity: 150,
        unit: "ml",
        category: "Proteínas",
      },
      {
        name: "Pechuga de pavo",
        quantity: 80,
        unit: "g",
        category: "Proteínas",
      },
      {
        name: "Pan integral",
        quantity: 1,
        unit: "rebanada",
        category: "Carbohidratos",
      },
      { name: "Tomate", quantity: 100, unit: "g", category: "Fruta y verdura" },
    ],
    preparation: [
      "Saltea el pavo.",
      "Añade huevo y claras y cuaja.",
      "Acompaña con pan y tomate.",
    ],
    tags: ["pan", "rápido"],
  },
  {
    mealType: "Cena",
    name: "Pavo salteado con verduras y arroz",
    description: "Cena completa con ración moderada de arroz.",
    calories: 560,
    protein: 51,
    carbs: 55,
    fat: 12,
    ingredients: [
      {
        name: "Pechuga de pavo",
        quantity: 200,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Arroz", quantity: 65, unit: "g", category: "Carbohidratos" },
      {
        name: "Calabacín",
        quantity: 150,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Pimiento",
        quantity: 100,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Aceite de oliva",
        quantity: 9,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Cuece el arroz.",
      "Saltea pavo y verduras.",
      "Sirve junto al arroz.",
    ],
    tags: ["alto en proteína", "ligera"],
  },
  {
    mealType: "Cena",
    name: "Ensalada templada de pollo y patata",
    description: "Ensalada saciante con pollo y patata asada.",
    calories: 545,
    protein: 49,
    carbs: 52,
    fat: 13,
    ingredients: [
      {
        name: "Pechuga de pollo",
        quantity: 190,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Patata", quantity: 250, unit: "g", category: "Carbohidratos" },
      { name: "Lechuga", quantity: 80, unit: "g", category: "Fruta y verdura" },
      { name: "Tomate", quantity: 100, unit: "g", category: "Fruta y verdura" },
      {
        name: "Aceite de oliva",
        quantity: 9,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Asa la patata y cocina el pollo.",
      "Monta la ensalada y sirve templada.",
    ],
    tags: ["ligera", "alto en proteína"],
  },
  {
    mealType: "Cena",
    name: "Hamburguesa de pollo con ensalada",
    description: "Hamburguesa casera sin exceso de grasa.",
    calories: 570,
    protein: 50,
    carbs: 53,
    fat: 16,
    ingredients: [
      {
        name: "Pechuga de pollo",
        quantity: 200,
        unit: "g",
        category: "Proteínas",
      },
      {
        name: "Pan de hamburguesa",
        quantity: 1,
        unit: "unidad",
        category: "Carbohidratos",
      },
      { name: "Lechuga", quantity: 60, unit: "g", category: "Fruta y verdura" },
      { name: "Tomate", quantity: 80, unit: "g", category: "Fruta y verdura" },
      { name: "Patata", quantity: 180, unit: "g", category: "Carbohidratos" },
    ],
    preparation: [
      "Forma y cocina la hamburguesa de pollo.",
      "Hornea la patata.",
      "Monta con ensalada.",
    ],
    tags: ["pan", "fin de semana"],
  },
  {
    mealType: "Cena",
    name: "Pasta de ternera y tomate",
    description: "Pasta con ternera magra y tomate, en ración controlada.",
    calories: 600,
    protein: 47,
    carbs: 66,
    fat: 16,
    ingredients: [
      { name: "Pasta", quantity: 75, unit: "g", category: "Carbohidratos" },
      {
        name: "Carne picada magra",
        quantity: 170,
        unit: "g",
        category: "Proteínas",
      },
      {
        name: "Tomate triturado",
        quantity: 180,
        unit: "g",
        category: "Fruta y verdura",
      },
      { name: "Cebolla", quantity: 60, unit: "g", category: "Fruta y verdura" },
      {
        name: "Aceite de oliva",
        quantity: 8,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Cuece la pasta.",
      "Cocina carne y cebolla con tomate.",
      "Mezcla y sirve.",
    ],
    tags: ["familiar", "alto en proteína"],
  },
];
