import type { PlannedMeal } from "@/features/nutrition-planner/types";

export type RecipeTemplate = Omit<PlannedMeal, "id">;

export const RECIPE_CATALOG: RecipeTemplate[] = [
  {
    mealType: "Desayuno",
    name: "Tostadas con pavo y tomate",
    description: "Desayuno salado con pan, proteína magra y fruta.",
    calories: 430,
    protein: 29,
    carbs: 55,
    fat: 10,
    ingredients: [
      {
        name: "Pan integral",
        quantity: 2,
        unit: "rebanada",
        category: "Carbohidratos",
      },
      {
        name: "Pechuga de pavo",
        quantity: 90,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Tomate", quantity: 120, unit: "g", category: "Fruta y verdura" },
      {
        name: "Aceite de oliva",
        quantity: 8,
        unit: "ml",
        category: "Despensa",
      },
      {
        name: "Plátano",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
    ],
    preparation: [
      "Tuesta el pan.",
      "Añade tomate, aceite y pavo.",
      "Sirve con el plátano.",
    ],
    tags: ["pan", "rápido", "alto en proteína"],
  },
  {
    mealType: "Desayuno",
    name: "Yogur con avena y frutos rojos",
    description: "Bol rápido y saciante para empezar el día.",
    calories: 410,
    protein: 28,
    carbs: 52,
    fat: 9,
    ingredients: [
      {
        name: "Yogur alto en proteína",
        quantity: 250,
        unit: "g",
        category: "Lácteos",
      },
      {
        name: "Copos de avena",
        quantity: 55,
        unit: "g",
        category: "Carbohidratos",
      },
      {
        name: "Frutos rojos",
        quantity: 120,
        unit: "g",
        category: "Fruta y verdura",
      },
      { name: "Miel", quantity: 10, unit: "g", category: "Despensa" },
    ],
    preparation: [
      "Mezcla el yogur y la avena.",
      "Añade los frutos rojos y la miel.",
    ],
    tags: ["sin cocinar", "alto en proteína"],
  },
  {
    mealType: "Media mañana",
    name: "Bocadillo pequeño de jamón y queso",
    description: "Tentempié práctico con pan y proteína.",
    calories: 330,
    protein: 22,
    carbs: 36,
    fat: 11,
    ingredients: [
      { name: "Pan", quantity: 90, unit: "g", category: "Carbohidratos" },
      { name: "Jamón cocido", quantity: 70, unit: "g", category: "Proteínas" },
      {
        name: "Queso bajo en grasa",
        quantity: 30,
        unit: "g",
        category: "Lácteos",
      },
    ],
    preparation: ["Abre el pan.", "Rellena con jamón y queso."],
    tags: ["pan", "portable"],
  },
  {
    mealType: "Media mañana",
    name: "Yogur proteico y manzana",
    description: "Opción ligera y fácil de llevar.",
    calories: 250,
    protein: 22,
    carbs: 31,
    fat: 4,
    ingredients: [
      {
        name: "Yogur alto en proteína",
        quantity: 200,
        unit: "g",
        category: "Lácteos",
      },
      {
        name: "Manzana",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
    ],
    preparation: ["Sirve el yogur junto a la manzana."],
    tags: ["sin cocinar", "portable"],
  },
  {
    mealType: "Comida",
    name: "Arroz con pollo y verduras",
    description: "Plato completo para días de entrenamiento.",
    calories: 690,
    protein: 52,
    carbs: 82,
    fat: 17,
    ingredients: [
      {
        name: "Pechuga de pollo",
        quantity: 190,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Arroz", quantity: 95, unit: "g", category: "Carbohidratos" },
      {
        name: "Calabacín",
        quantity: 150,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Pimiento",
        quantity: 100,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Aceite de oliva",
        quantity: 12,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Cuece el arroz.",
      "Saltea pollo y verduras con aceite.",
      "Mezcla y sazona.",
    ],
    tags: ["entrenamiento", "alto en proteína"],
  },
  {
    mealType: "Comida",
    name: "Pasta boloñesa ligera",
    description: "Pasta con carne magra y tomate.",
    calories: 720,
    protein: 49,
    carbs: 88,
    fat: 19,
    ingredients: [
      { name: "Pasta", quantity: 100, unit: "g", category: "Carbohidratos" },
      {
        name: "Carne picada magra",
        quantity: 180,
        unit: "g",
        category: "Proteínas",
      },
      {
        name: "Tomate triturado",
        quantity: 200,
        unit: "g",
        category: "Fruta y verdura",
      },
      { name: "Cebolla", quantity: 80, unit: "g", category: "Fruta y verdura" },
      {
        name: "Aceite de oliva",
        quantity: 10,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Cuece la pasta.",
      "Sofríe cebolla y carne.",
      "Añade tomate y mezcla con la pasta.",
    ],
    tags: ["alto en proteína", "familiar"],
  },
  {
    mealType: "Comida",
    name: "Patatas asadas con pavo",
    description: "Comida saciante con proteína magra.",
    calories: 650,
    protein: 50,
    carbs: 73,
    fat: 17,
    ingredients: [
      {
        name: "Pechuga de pavo",
        quantity: 200,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Patata", quantity: 380, unit: "g", category: "Carbohidratos" },
      {
        name: "Ensalada variada",
        quantity: 180,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Aceite de oliva",
        quantity: 12,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Asa las patatas.",
      "Cocina el pavo a la plancha.",
      "Sirve con ensalada.",
    ],
    tags: ["sin pescado", "alto en proteína"],
  },
  {
    mealType: "Merienda",
    name: "Sándwich de tortilla francesa",
    description: "Merienda completa y sencilla.",
    calories: 380,
    protein: 25,
    carbs: 34,
    fat: 16,
    ingredients: [
      {
        name: "Pan integral",
        quantity: 2,
        unit: "rebanada",
        category: "Carbohidratos",
      },
      { name: "Huevo", quantity: 2, unit: "unidad", category: "Proteínas" },
      {
        name: "Claras de huevo",
        quantity: 120,
        unit: "ml",
        category: "Proteínas",
      },
      { name: "Tomate", quantity: 70, unit: "g", category: "Fruta y verdura" },
    ],
    preparation: [
      "Prepara la tortilla con huevo y claras.",
      "Monta el sándwich con tomate.",
    ],
    tags: ["pan", "alto en proteína"],
  },
  {
    mealType: "Merienda",
    name: "Batido de plátano y yogur",
    description: "Merienda rápida para después de entrenar.",
    calories: 360,
    protein: 28,
    carbs: 54,
    fat: 5,
    ingredients: [
      {
        name: "Yogur alto en proteína",
        quantity: 250,
        unit: "g",
        category: "Lácteos",
      },
      {
        name: "Plátano",
        quantity: 1,
        unit: "unidad",
        category: "Fruta y verdura",
      },
      {
        name: "Copos de avena",
        quantity: 35,
        unit: "g",
        category: "Carbohidratos",
      },
      { name: "Leche", quantity: 150, unit: "ml", category: "Lácteos" },
    ],
    preparation: [
      "Tritura todos los ingredientes hasta obtener una textura homogénea.",
    ],
    tags: ["postentreno", "rápido"],
  },
  {
    mealType: "Cena",
    name: "Tortilla de patata ligera con ensalada",
    description: "Cena casera con cantidad controlada de aceite.",
    calories: 560,
    protein: 35,
    carbs: 54,
    fat: 23,
    ingredients: [
      { name: "Huevo", quantity: 3, unit: "unidad", category: "Proteínas" },
      {
        name: "Claras de huevo",
        quantity: 150,
        unit: "ml",
        category: "Proteínas",
      },
      { name: "Patata", quantity: 260, unit: "g", category: "Carbohidratos" },
      {
        name: "Ensalada variada",
        quantity: 180,
        unit: "g",
        category: "Fruta y verdura",
      },
      {
        name: "Aceite de oliva",
        quantity: 8,
        unit: "ml",
        category: "Despensa",
      },
    ],
    preparation: [
      "Cocina la patata al microondas o al horno.",
      "Cuaja con huevo y claras.",
      "Sirve con ensalada.",
    ],
    tags: ["sin pescado", "cena"],
  },
  {
    mealType: "Cena",
    name: "Wraps de pollo y verduras",
    description: "Cena rápida con pollo y vegetales.",
    calories: 580,
    protein: 46,
    carbs: 61,
    fat: 17,
    ingredients: [
      {
        name: "Tortilla de trigo",
        quantity: 2,
        unit: "unidad",
        category: "Carbohidratos",
      },
      {
        name: "Pechuga de pollo",
        quantity: 170,
        unit: "g",
        category: "Proteínas",
      },
      { name: "Lechuga", quantity: 80, unit: "g", category: "Fruta y verdura" },
      { name: "Tomate", quantity: 100, unit: "g", category: "Fruta y verdura" },
      { name: "Yogur natural", quantity: 60, unit: "g", category: "Lácteos" },
    ],
    preparation: [
      "Cocina el pollo.",
      "Rellena las tortillas con verduras y pollo.",
      "Añade yogur como salsa.",
    ],
    tags: ["rápido", "alto en proteína"],
  },
  {
    mealType: "Cena",
    name: "Hamburguesa casera con patata",
    description: "Cena completa con carne magra y pan.",
    calories: 670,
    protein: 48,
    carbs: 70,
    fat: 22,
    ingredients: [
      {
        name: "Carne picada magra",
        quantity: 180,
        unit: "g",
        category: "Proteínas",
      },
      {
        name: "Pan de hamburguesa",
        quantity: 1,
        unit: "unidad",
        category: "Carbohidratos",
      },
      { name: "Patata", quantity: 260, unit: "g", category: "Carbohidratos" },
      { name: "Lechuga", quantity: 50, unit: "g", category: "Fruta y verdura" },
      { name: "Tomate", quantity: 80, unit: "g", category: "Fruta y verdura" },
    ],
    preparation: [
      "Forma y cocina la hamburguesa.",
      "Hornea la patata.",
      "Monta con lechuga y tomate.",
    ],
    tags: ["pan", "fin de semana"],
  },
];
